// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ResetFormController from "./reset_form_controller"
application.register("reset_form", ResetFormController)

import ResetScrollController from "./reset_scroll_controller"
application.register("reset_scroll", ResetScrollController)