version: '3'
services:
  redis:
    image: redis:alpine
    expose:
      - 7000
    ports:
      - 7000
    volumes:
      - redis_data:/data
    command: --port 7000
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500' -p 54320"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    expose:
      - 54320
    ports:
      - "54320:54320"
  selenium:
    image: selenium/standalone-chrome:124.0
    ports:
      - "5900:5900" #for VNC access
      - "4444:4444" #for webdriver access
      - "7900:7900" #for web VNC access
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_PORT: 54320
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
      REDIS_URL: "redis://redis:7000/1"
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
      - selenium
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
networks:
  default:
    name: live-chat_network